package com.habbitat.app.verification

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import android.util.Base64
import com.habbitat.app.BuildConfig
import com.habbitat.app.data.local.entity.Habit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.InputStream
import java.util.concurrent.TimeUnit

class VisionApiProofVerifier : ProofVerifier {

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    override suspend fun verify(habit: Habit, imageUri: Uri, context: Context): VerificationResult {
        val apiKey = BuildConfig.OPENROUTER_API_KEY.ifBlank { BuildConfig.AI_VERIFICATION_API_KEY }.trim()

        // Rule: If key is blank, honestly return unconfigured state (INSTRUCTIONS.md §2)
        if (apiKey.isBlank()) {
            return VerificationResult(
                verified = false,
                confidence = 0.0f,
                reason = "API key not configured yet. Add AI_VERIFICATION_API_KEY to local.properties."
            )
        }

        return withContext(Dispatchers.IO) {
            try {
                val base64Image = convertUriToBase64(context, imageUri)
                    ?: return@withContext VerificationResult(
                        verified = false,
                        confidence = 0.0f,
                        reason = "Failed to process photo image data."
                    )

                val promptText = """
                    You are an AI proof verifier for the habit: "${habit.name}".
                    Required proof requirement: "${habit.proofDescription.ifBlank { "Photo of habit completion" }}".
                    Analyze the attached image. Does this photo genuinely show proof of completing this habit?
                    Output ONLY valid JSON with this exact structure, no markdown wrappers:
                    {"verified": boolean, "confidence": float_between_0_and_1, "reason": "short detailed explanation"}
                """.trimIndent()

                // Construct OpenAI / OpenRouter vision completion payload
                val payload = JSONObject().apply {
                    put("model", "google/gemini-2.5-flash")
                    put("messages", JSONArray().apply {
                        put(JSONObject().apply {
                            put("role", "user")
                            put("content", JSONArray().apply {
                                put(JSONObject().apply {
                                    put("type", "text")
                                    put("text", promptText)
                                })
                                put(JSONObject().apply {
                                    put("type", "image_url")
                                    put("image_url", JSONObject().apply {
                                        put("url", "data:image/jpeg;base64,$base64Image")
                                    })
                                })
                            })
                        })
                    })
                    put("max_tokens", 300)
                }

                val baseUrl = "https://openrouter.ai/api/v1/chat/completions"

                val request = Request.Builder()
                    .url(baseUrl)
                    .addHeader("Authorization", "Bearer $apiKey")
                    .addHeader("Content-Type", "application/json")
                    .post(payload.toString().toRequestBody("application/json".toMediaType()))
                    .build()

                val response = client.newCall(request).execute()
                val responseBody = response.body?.string() ?: ""

                if (!response.isSuccessful) {
                    return@withContext VerificationResult(
                        verified = false,
                        confidence = 0.0f,
                        reason = "Vision API HTTP error ${response.code}: $responseBody"
                    )
                }

                val jsonResponse = JSONObject(responseBody)
                val choices = jsonResponse.getJSONArray("choices")
                if (choices.length() == 0) {
                    return@withContext VerificationResult(
                        verified = false,
                        confidence = 0.0f,
                        reason = "No response generated by Vision AI backend."
                    )
                }

                val contentText = choices.getJSONObject(0)
                    .getJSONObject("message")
                    .getString("content")
                    .trim()

                parseVerificationJson(contentText)
            } catch (e: Exception) {
                VerificationResult(
                    verified = false,
                    confidence = 0.0f,
                    reason = "Verification error: ${e.localizedMessage ?: "Unknown error"}"
                )
            }
        }
    }

    private fun parseVerificationJson(jsonText: String): VerificationResult {
        return try {
            val cleanJson = jsonText
                .replace("```json", "")
                .replace("```", "")
                .trim()

            val json = JSONObject(cleanJson)
            val isVerified = json.optBoolean("verified", false)
            val confidence = json.optDouble("confidence", 0.0).toFloat()
            val reason = json.optString("reason", "Verification processed.")

            // Apply threshold rules per phase-3 spec:
            // High (>= 0.70) -> auto-accept
            // Medium (0.40 - 0.69) -> ask clarification / flag
            // Low (< 0.40) -> reject
            val finalVerified = isVerified && confidence >= 0.70f

            VerificationResult(
                verified = finalVerified,
                confidence = confidence,
                reason = reason
            )
        } catch (e: Exception) {
            VerificationResult(
                verified = false,
                confidence = 0.0f,
                reason = "AI output formatting error: $jsonText"
            )
        }
    }

    private fun convertUriToBase64(context: Context, uri: Uri): String? {
        return try {
            val inputStream: InputStream? = context.contentResolver.openInputStream(uri)
            val bitmap = BitmapFactory.decodeStream(inputStream)
            inputStream?.close()

            // Scale down bitmap to max 1024x1024 to optimize payload
            val maxDimension = 1024
            val scaledBitmap = if (bitmap.width > maxDimension || bitmap.height > maxDimension) {
                val ratio = minOf(
                    maxDimension.toFloat() / bitmap.width,
                    maxDimension.toFloat() / bitmap.height
                )
                Bitmap.createScaledBitmap(
                    bitmap,
                    (bitmap.width * ratio).toInt(),
                    (bitmap.height * ratio).toInt(),
                    true
                )
            } else {
                bitmap
            }

            val outputStream = ByteArrayOutputStream()
            scaledBitmap.compress(Bitmap.CompressFormat.JPEG, 85, outputStream)
            val byteArray = outputStream.toByteArray()
            Base64.encodeToString(byteArray, Base64.NO_WRAP)
        } catch (e: Exception) {
            null
        }
    }
}
